SETX DATABASE_SERVICE_PORT "8083"
SETX DATABASE_TOKEN_SERVICE_PORT "8084"
SETX DRIVE_SERVICE_PORT "8085"
SETX MAIL_SERVICE_PORT "8081"
SETX IMAGE_SERVICE_PORT "8082"
SETX IDENTITY_SERVICE_PORT "8080"
SETX RESOURCE_PROVIDER_SERVICE_PORT "8086"

SETX DATABASE_SERVICE_URL "http://localhost:%DATABASE_SERVICE_PORT%/"
SETX DATABASE_TOKEN_SERVICE_URL "http://localhost:%DATABASE_TOKEN_SERVICE_PORT%/"
SETX DRIVE_SERVICE_URL "http://localhost:%DRIVE_SERVICE_PORT%/"
SETX MAIL_SERVICE_URL "http://localhost:%MAIL_SERVICE_PORT%/"
SETX IMAGE_SERVICE_URL "http://localhost:%IMAGE_SERVICE_PORT%/"
SETX IDENTITY_SERVICE_URL "http://localhost:%IDENTITY_SERVICE_PORT%/"
SETX RESOURCE_PROVIDER_SERVICE_URL "http://localhost:%RESOURCE_PROVIDER_SERVICE_PORT%/"

SETX SERVICE_TOKEN "123"
SETX MAX_FILE_SIZE_UPLOAD "5242800"
SETX MAX_IMAGE_SIZE_UPLOAD "5242800"

SETX POSTGRESQL_USERNAME "postgres"
SETX POSTGRESQL_PASSWORD "0000"
SETX POSTGRESQL_SCHEMA "public"
SETX POSTGRESQL_URL "localhost:5432"
SETX POSTGRESQL_DATABASE_NAME "postgres"

SETX SMTPS_HOST "smtp.gmail.com"
SETX SMTPS_USER "studschedapp@gmail.com"

SETX SMTPS_PASSWORD "njvkbgevrmwvinjz"

SETX GOOGLE_APP_NAME "StudentScheduleApp"
SETX YANDEX_OAUTH_TOKEN "y0_AgAAAAB0gfDGAAvSigAAAAEFbCekAACJiyBc4LpCH6v_-3LhRboqrurdOQ"

SETX JWT_SECRET_ACCESS "qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w=="
SETX JWT_SECRET_REFRESH "zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg=="








